version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile-alpine
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - mariadb

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/html:ro
    ports:
      - "8000:80"
    networks:
      - app-network
    depends_on:
      - php

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}  # Change this for your production setup
      MYSQL_DATABASE: ${DATABASE_NAME} # Database name to be created
      MYSQL_USER: ${DATABASE_USER}  # User for accessing the DB
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}  # User password
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
